workflows:
  unsigned-rn-android:
    name: Unsigned React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17

    scripts:
      - name: Debug print current directory
        script: |
          echo "PWD is: $(pwd)"
          echo "Files here:"
          ls -la

      - name: Setup Yarn
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "📦 Ensuring Yarn Berry is active"
          corepack enable
          corepack prepare yarn@3.6.4 --activate
          yarn --version

      - name: Install dependencies
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "📦 Installing project dependencies..."
          yarn install --immutable
          echo "✅ Dependencies installed successfully"

      - name: Build unsigned Android APK
        working_directory: android
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "🏗️ Building unsigned APK..."
          ./gradlew assembleRelease -x signReleaseBundle
          echo "✅ Build finished"

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
