workflows:
  unsigned-rn-android:
    name: Unsigned React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17

    scripts:
      - name: Debug print current directory
        script: |
          echo "PWD is: $(pwd)"
          echo "Files here:"
          ls -la

      - name: Setup Yarn
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          if [ -f ".yarnrc.yml" ]; then
            echo "📦 Yarn Berry detected"
            corepack enable
            corepack prepare yarn@3.6.4 --activate
          else
            echo "📦 Yarn v1 detected (already installed on Codemagic)"
            yarn --version
          fi

      - name: Install dependencies
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "📦 Installing project dependencies..."

          if [ -f ".yarnrc.yml" ]; then
            echo "Detected Yarn Berry (v2/v3)"
            yarn install
          else
            echo "Detected Yarn v1"
            yarn install --ignore-engines
          fi

          echo "✅ Dependencies installed successfully"

      - name: Build unsigned Android APK
        working_directory: android
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "🏗️ Building unsigned APK..."
          ./gradlew assembleRelease -x signReleaseBundle
          echo "✅ Build finished"

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
