workflows:
  unsigned-build:
    name: Unsigned Android & iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      # Android Build
      - name: Build unsigned Android APK
        script: flutter build apk --release --no-sign
      # OR for AAB
      # script: flutter build appbundle --release --no-sign

      # iOS Build (without signing)
      - name: Build iOS app (no signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
      - build/ios/iphoneos/*.app
      - build/ios/archive/*.xcarchive
