workflows:
  unsigned-rn-android:
    name: Unsigned React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: Setup and install dependencies
        working_directory: /usr/mobile-app/MobileCICD
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          # Detect Yarn version
          if [ -f ".yarnrc.yml" ]; then
            echo "📦 Yarn Berry (v2/v3) detected"
            corepack enable || true
            corepack prepare yarn@3.6.4 --activate || true
          else
            echo "📦 Yarn v1 detected (default on Codemagic)"
            npm install -g yarn || true
          fi

          # Install JS dependencies
          yarn install --ignore-engines

          # If iOS folder exists, install pods (skip if not present)
          if [ -d "ios" ]; then
            echo "📱 Installing CocoaPods dependencies"
            cd ios
            pod install --repo-update
            cd ..
          else
            echo "ℹ️ Skipping iOS setup (no ios/ directory found)"
          fi

      - name: Build unsigned Android APK
        working_directory: /usr/mobile-app/MobileCICD/android
        script: ./gradlew assembleRelease -x signReleaseBundle

    artifacts:
      - /usr/mobile-app/MobileCICD/android/app/build/outputs/apk/release/*.apk
      - /usr/mobile-app/MobileCICD/android/app/build/outputs/bundle/release/*.aab
