workflows:
  unsigned-rn-android:
    name: Unsigned React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: Debug: print current directory
        script: |
          echo "PWD is: $(pwd)"
          echo "Files here:"
          ls -la

      - name: Setup Yarn
        script: |
          if [ -f ".yarnrc.yml" ]; then
            echo "Yarn Berry detected"
            corepack enable
            corepack prepare yarn@3.6.4 --activate
          else
            echo "Yarn v1 detected"
            npm install -g yarn
          fi

      - name: Install dependencies
        script: yarn install --ignore-engines

      - name: Build unsigned Android APK
        working_directory: android
        script: ./gradlew assembleRelease -x signReleaseBundle

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
