workflows:
  unsigned-rn-android:
    name: Unsigned React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd $CM_BUILD_DIR
          yarn install

      - name: Build unsigned Android APK
        script: |
          cd android
          ./gradlew assembleRelease -x signReleaseBundle

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
