workflows:
  unsigned-rn-android:
    name: Unsigned React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: "Debug: show directory tree"
        working_directory: /Users/builder/clone
        script: |
          echo "📂 Current directory: $(pwd)"
          ls -R | head -50

      - name: Setup Yarn
        working_directory: /Users/builder/clone/usr/mobile-app/MobileCICD
        script: |
          if [ -f ".yarnrc.yml" ]; then
            echo "📦 Yarn Berry detected"
            corepack enable || true
            corepack prepare yarn@3.6.4 --activate || true
          else
            echo "📦 Yarn v1 detected"
            if ! command -v yarn &> /dev/null; then
              npm install -g yarn
            else
              echo "ℹ️ Yarn already installed"
            fi
          fi

      - name: Install dependencies
        working_directory: /Users/builder/clone/usr/mobile-app/MobileCICD
        script: |
          echo "📦 Installing project dependencies..."
          yarn install
          echo "✅ Dependencies installed"

      - name: Build unsigned Android APK
        working_directory: /Users/builder/clone/usr/mobile-app/MobileCICD/android
        script: ./gradlew assembleRelease -x signReleaseBundle

    artifacts:
      - /Users/builder/clone/usr/mobile-app/MobileCICD/android/app/build/outputs/apk/release/*.apk
      - /Users/builder/clone/usr/mobile-app/MobileCICD/android/app/build/outputs/bundle/release/*.aab
