workflows:
  unsigned-rn-build:
    name: Unsigned React Native Android & iOS Build
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          yarn install
          cd ios && pod install --repo-update && cd ..

      # Android unsigned build
      - name: Build unsigned Android APK
        script: |
          cd android
          ./gradlew assembleRelease -x signReleaseBundle
          cd ..

      # iOS unsigned build
      - name: Build iOS app (no codesign)
        script: |
          cd ios
          xcodebuild \
            -workspace YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/ios/archive/YourApp.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO
          cd ..

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
      - ios/archive/*.xcarchive
