workflows:
  unsigned-rn-android:
    name: Unsigned React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: Setup Yarn
        working_directory: /Users/builder/clone
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          
          if [ -f ".yarnrc.yml" ]; then
            echo "📦 Yarn Berry (v2/v3) detected"
            corepack enable || true
            corepack prepare yarn@3.6.4 --activate || true
          else
            echo "📦 Yarn v1 detected"
            # Yarn is usually preinstalled on Codemagic
            if ! command -v yarn &> /dev/null; then
              npm install -g yarn
            else
              echo "ℹ️ Yarn already installed, skipping npm install"
            fi
          fi

      - name: Install dependencies
        working_directory: /Users/builder/clone
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "📦 Installing project dependencies..."
          yarn install --immutable
          echo "✅ Dependencies installed successfully"

      - name: Build unsigned Android APK
        working_directory: /Users/builder/clone/android
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "🏗️ Building unsigned APK..."
          ./gradlew assembleRelease -x signReleaseBundle
          echo "✅ APK build finished"

    artifacts:
      - /Users/builder/clone/android/app/build/outputs/apk/release/*.apk
      - /Users/builder/clone/android/app/build/outputs/bundle/release/*.aab
